### ISSUE TITLE
Include dependencies on bourbon and neat

### ISSUE THREAD

**Issue by alexeygrinko-xo** [CrazyEggInc/whisper-burner#3]
Currently when using whisper-burner, we have to include dependencies on bourbon and neat each time.
We should either include those into the repo directly, or get rid of the dependencies at all (preferable).
CC @christopherlai 

Note that Shopify app will also depend on this repo, so be careful when introducing new changes here. Maybe we should use proper versioning with each update

**Comment by christopherlai** [comment]
@alexeygrinko-xo I created a PR to address this. Take a look and let me know what you think.

https://github.com/CrazyEggInc/whisper-burner/pull/5

We use tags for version control on all dependences already. Pushing to master should not break apps that depend on WB.

**Comment by alexeygrinko-xo** [comment]
@christopherlai , looks good 👍

**Comment by alexeygrinko-xo** [comment]
@christopherlai , I can't get it working now via package.json.
If I install with yarn/npm, there is an error:
```
File to import not found or unreadable: bourbon.
Load paths:
  /home/osboxes/shopify-app/app/assets/config
  /home/osboxes/shopify-app/app/assets/images
  /home/osboxes/shopify-app/app/assets/javascripts
  /home/osboxes/shopify-app/app/assets/stylesheets
  /home/osboxes/.rvm/gems/ruby-2.5.1/gems/bourbon-4.3.4/app/assets/stylesheets
  /home/osboxes/.rvm/gems/ruby-2.5.1/gems/shopify_app-8.2.6/app/assets/javascripts
  /home/osboxes/.rvm/gems/ruby-2.5.1/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /home/osboxes/.rvm/gems/ruby-2.5.1/gems/actioncable-5.2.0/lib/assets/compiled
  /home/osboxes/.rvm/gems/ruby-2.5.1/gems/activestorage-5.2.0/app/assets/javascripts
  /home/osboxes/.rvm/gems/ruby-2.5.1/gems/actionview-5.2.0/lib/assets/compiled
  /home/osboxes/.rvm/gems/ruby-2.5.1/gems/turbolinks-source-5.1.0/lib/assets/javascripts
  /home/osboxes/shopify-app/node_modules
```
Bourbon and Neat exist in `node_modules` directory as expected, but they cannot be imported as simple as `@import "bourbon"`. Instead, `@import "bourbon/app/assets/stylesheets/bourbon"` works. That's because SASS import requires concrete path to the scss file, it doesn't read those `includePaths` from `index.js` (at least in Ruby on Rails app).

Here's what I found about this issue: https://github.com/thoughtbot/bourbon#installing-with-npm-and-using-a-node-based-asset-pipeline
So looks like `node-sass` should be modified to include paths from bourbon module. If we do so from main app, it means it still depends directly on bourbon. Whisper burner package should be self-contained, but I'm not sure how to fix this issue. At least describe it in Readme to not puzzle somebody else.

_______________
Nevertheless, it worked via Gemfile with ruby. So maybe we should just not support package.json way and make it only available as a Ruby gem.

I installed it with:
`gem 'whisper_burner', git: 'https://github.com/CrazyEggInc/whisper-burner.git', tag: 'v2.1'`

I had hard times trying to import it as `@import "whisper_burner"` in SCSS file, while I should use "whisper-burner" (dash instead of underscore). It really needs some documentation 😄

**Comment by christopherlai** [comment]
@alexeygrinko-xo in a Rails app we should use the gem. I only added the NPM version because we still need it for Core Application. When I tested it there, it worked.

I took a look at how it was being used in the Shopify App and it looks like using the gem format is best there.

**Comment by alexeygrinko-xo** [comment]
@christopherlai , ok, didn't know that! Then just take some time in future to update the readme to help other newbies like me 😸

**Comment by christopherlai** [comment]
@alexeygrinko-xo I agree. My solo goal was to get you something that you could use aka please Alexey hahaha
